# Generated by Django 6.0.6 on 2026-06-04 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('microcredits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé (FCFA)')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Echeancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('montant_attendu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant attendu (FCFA)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('demande_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeanciers', to='microcredits.demandecredit', verbose_name='Demande de Crédit')),
            ],
            options={
                'verbose_name': 'Échéancier',
                'verbose_name_plural': 'Échéanciers',
                'ordering': ['date_echeance'],
            },
        ),
    ]
