# Generated by Django 4.2.10 on 2026-06-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remboursements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeancier',
            name='penalite_retard',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pénalité de retard'),
        ),
    ]
