# Generated by Django 6.0.6 on 2026-06-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='sujet',
            field=models.CharField(default='Demande de support', max_length=255, verbose_name='Sujet'),
        ),
    ]
