# Generated by Django 6.0.6 on 2026-06-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_client', '0003_conversation_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lu',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
    ]
