# Generated by Django 6.0.6 on 2026-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('message', models.TextField(verbose_name='Message de la notification')),
                ('type_alerte', models.CharField(choices=[('INFO', 'Information'), ('CREDIT', 'Mise à jour Crédit'), ('PAIEMENT', 'Paiement Enregistré'), ('ASSURANCE', 'Alerte Assurance')], default='INFO', max_length=20, verbose_name="Type d'alerte")),
                ('est_lue', models.BooleanField(default=False, verbose_name='Est lue ?')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
