# Generated by Django 6.0.6 on 2026-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant demandé (FCFA)')),
                ('duree_mois', models.PositiveIntegerField(verbose_name='Durée en mois')),
                ('justificatifs', models.FileField(blank=True, null=True, upload_to='justificatifs_credits/', verbose_name='Pièces justificatives')),
                ('score_eligibilite', models.IntegerField(blank=True, null=True, verbose_name="Score d'éligibilité")),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En analyse'), ('APPROUVEE', 'Approuvée'), ('DECAISSEE', 'Décaissée')], default='SOUMISE', max_length=20, verbose_name='Statut de la demande')),
            ],
            options={
                'verbose_name': 'Demande de Crédit',
                'verbose_name_plural': 'Demandes de Crédit',
            },
        ),
    ]
