# Generated by Django 6.0.6 on 2026-06-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecredit',
            name='statut',
            field=models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_ANALYSE', 'En analyse'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('DECAISSEE', 'Décaissée')], default='SOUMISE', max_length=20, verbose_name='Statut de la demande'),
        ),
    ]
