# Generated by Django 6.0.6 on 2026-06-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredits', '0003_alter_demandecredit_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='note_decision',
            field=models.TextField(blank=True, null=True, verbose_name='Note de décision'),
        ),
    ]
