# Generated by Django 6.0.6 on 2026-06-11 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredits', '0004_demandecredit_note_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='admin_approbation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_approuvees', to=settings.AUTH_USER_MODEL, verbose_name="Administrateur d'approbation"),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='agent_analyse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_analysees', to=settings.AUTH_USER_MODEL, verbose_name="Agent d'analyse"),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='date_analyse',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'analyse"),
        ),
        migrations.AddField(
            model_name='demandecredit',
            name='date_approbation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation"),
        ),
    ]
