# Generated by Django 6.0.6 on 2026-06-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcredits', '0005_demandecredit_admin_approbation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecredit',
            name='motif',
            field=models.TextField(blank=True, null=True, verbose_name='Motif / Justification'),
        ),
    ]
